/**
 * Export format generators for SYPI canvases.
 * Produces: Mermaid, spi-schema JSON, CLAUDE.md, TASKS.md, Lovable/v0 prompts, ZIP bundle.
 */

import type { CanvasNode, CanvasEdge, NodeCategory } from "@/types/canvas";

// ─── spi-schema (canonical import/export format) ─────────────────────────────

export interface SpiSchema {
  version: "1";
  meta: {
    projectName: string;
    exportedAt: string;
    exportedBy: string;
  };
  nodes: Array<{
    id: string;
    type: string;
    position: { x: number; y: number };
    data: Record<string, unknown>;
  }>;
  edges: Array<{
    id: string;
    source: string;
    target: string;
    type?: string;
    data?: Record<string, unknown>;
  }>;
}

export function generateSpiSchema(
  nodes: CanvasNode[],
  edges: CanvasEdge[],
  projectName: string
): SpiSchema {
  return {
    version: "1",
    meta: {
      projectName: projectName || "Untitled Project",
      exportedAt: new Date().toISOString().slice(0, 10),
      exportedBy: "SYPI",
    },
    nodes: nodes.map((n) => ({
      id: n.id,
      type: n.type ?? "systemNode",
      position: { x: Math.round(n.position.x), y: Math.round(n.position.y) },
      data: { ...n.data } as Record<string, unknown>,
    })),
    edges: edges.map((e) => ({
      id: e.id,
      source: e.source,
      target: e.target,
      type: e.type,
      data: e.data as Record<string, unknown> | undefined,
    })),
  };
}

// ─── Mermaid ─────────────────────────────────────────────────────────────────

const MERMAID_SHAPE: Record<NodeCategory, [string, string]> = {
  client:   ["[",  "]"],
  gateway:  ["{",  "}"],
  service:  ["[",  "]"],
  compute:  ["[/", "/]"],
  queue:    ["([", "])"],
  cache:    ["([", "])"],
  database: ["[(", ")]"],
  storage:  ["[(", ")]"],
  custom:   ["[",  "]"],
};

function mermaidId(id: string): string {
  return id.replace(/[^a-zA-Z0-9_]/g, "_");
}

export function generateMermaid(nodes: CanvasNode[], edges: CanvasEdge[]): string {
  const idToLabel = new Map<string, string>();
  for (const n of nodes) {
    idToLabel.set(n.id, (n.data.label as string) || "Untitled");
  }

  const lines = ["flowchart LR"];

  for (const n of nodes) {
    const label = (n.data.label as string) || "Untitled";
    const category = (n.data.nodeCategory as NodeCategory) || "custom";
    const [open, close] = MERMAID_SHAPE[category] ?? ["[", "]"];
    const safe = label.replace(/"/g, "'");
    lines.push(`  ${mermaidId(n.id)}${open}"${safe}"${close}`);
  }

  if (edges.length > 0) lines.push("");

  for (const e of edges) {
    const edgeLabel = (e.data?.label as string)?.trim();
    const src = mermaidId(e.source);
    const tgt = mermaidId(e.target);
    if (edgeLabel) {
      lines.push(`  ${src} -->|"${edgeLabel.replace(/"/g, "'")}"| ${tgt}`);
    } else {
      lines.push(`  ${src} --> ${tgt}`);
    }
  }

  return lines.join("\n");
}

// ─── Agent bundle files ───────────────────────────────────────────────────────

function groupNodesByTier(nodes: CanvasNode[]) {
  const frontend: CanvasNode[] = [];
  const backend: CanvasNode[] = [];
  const infra: CanvasNode[] = [];
  const data: CanvasNode[] = [];

  for (const n of nodes) {
    const cat = (n.data.nodeCategory as NodeCategory) || "custom";
    if (cat === "client") frontend.push(n);
    else if (cat === "service" || cat === "compute") backend.push(n);
    else if (cat === "gateway" || cat === "queue" || cat === "cache") infra.push(n);
    else if (cat === "database" || cat === "storage") data.push(n);
    else backend.push(n);
  }

  return { frontend, backend, infra, data };
}

export function generateClaudeMd(
  nodes: CanvasNode[],
  edges: CanvasEdge[],
  projectName: string,
  specMarkdown: string
): string {
  const { frontend, backend, infra, data } = groupNodesByTier(nodes);
  const idToLabel = new Map<string, string>();
  for (const n of nodes) idToLabel.set(n.id, (n.data.label as string) || "Untitled");

  const nodeList = (arr: CanvasNode[]) =>
    arr.length === 0
      ? "  (none)\n"
      : arr
          .map((n) => {
            const desc = (n.data.description as string)?.trim();
            const tech = (n.data.configTechnology as string)?.trim();
            return `  - **${n.data.label || "Untitled"}**${tech ? ` (${tech})` : ""}${desc ? `: ${desc}` : ""}`;
          })
          .join("\n") + "\n";

  const flowSummary = edges
    .slice(0, 10)
    .map((e) => {
      const src = idToLabel.get(e.source) ?? e.source;
      const tgt = idToLabel.get(e.target) ?? e.target;
      const lbl = (e.data?.label as string)?.trim();
      return `  - ${src} → ${tgt}${lbl ? ` (${lbl})` : ""}`;
    })
    .join("\n");

  return `# ${projectName} — Agent Context

> Generated by SYPI. Feed this file to Claude Code, Codex, or any AI coding agent
> to give it full context on what to build and how.

## Files in this bundle

| File | Purpose |
|------|---------|
| \`CLAUDE.md\` | This file — agent context and architecture summary |
| \`ARCHITECTURE.md\` | Full technical spec (human-readable) |
| \`spi-schema.json\` | Machine-readable canvas (re-import into SYPI) |
| \`TASKS.md\` | Ordered implementation task list |

## System: ${projectName}

${nodes.length} components, ${edges.length} connections.

## Architecture by tier

### Frontend / Clients
${nodeList(frontend)}
### Backend Services
${nodeList(backend)}
### Infrastructure
${nodeList(infra)}
### Data Layer
${nodeList(data)}
## Key data flows

${flowSummary || "  (no connections defined yet)"}

## How to use this context

1. Read \`ARCHITECTURE.md\` for the full spec
2. Follow \`TASKS.md\` in order — each task maps to one or more components above
3. The \`spi-schema.json\` is the canonical source of truth for component names and relationships
4. When implementing a service, check its incoming and outgoing edges for the expected API contracts

## Conventions expected by this system

- TypeScript throughout
- API routes follow REST conventions unless a component specifies otherwise
- Environment variables for all secrets and external URLs
- Each service should be independently testable

---
_Re-import \`spi-schema.json\` into SYPI at any time to continue designing._
`;
}

export function generateTasksMd(
  nodes: CanvasNode[],
  edges: CanvasEdge[],
  projectName: string
): string {
  const { frontend, backend, infra, data } = groupNodesByTier(nodes);
  const idToLabel = new Map<string, string>();
  for (const n of nodes) idToLabel.set(n.id, (n.data.label as string) || "Untitled");

  const taskBlock = (title: string, items: CanvasNode[]) => {
    if (items.length === 0) return "";
    const tasks = items.map((n) => {
      const label = (n.data.label as string) || "Untitled";
      const tech = (n.data.configTechnology as string)?.trim();
      const incoming = edges
        .filter((e) => e.target === n.id)
        .map((e) => idToLabel.get(e.source))
        .filter(Boolean);
      const outgoing = edges
        .filter((e) => e.source === n.id)
        .map((e) => idToLabel.get(e.target))
        .filter(Boolean);
      const connections =
        [...incoming.map((s) => `← ${s}`), ...outgoing.map((t) => `→ ${t}`)].join(", ");
      return `- [ ] **${label}**${tech ? ` (${tech})` : ""}${connections ? `  _[${connections}]_` : ""}`;
    });
    return `## ${title}\n\n${tasks.join("\n")}\n\n`;
  };

  return `# Implementation Tasks — ${projectName}

Generated by SYPI. Work through these phases in order.

## Phase 0: Project Setup

- [ ] Initialise project (framework, package manager, TypeScript config)
- [ ] Set up environment variables file
- [ ] Configure linting and formatting
- [ ] Set up CI pipeline

${taskBlock("Phase 1: Data Layer", data)}${taskBlock("Phase 2: Infrastructure", infra)}${taskBlock("Phase 3: Backend Services", backend)}${taskBlock("Phase 4: Frontend", frontend)}## Phase 5: Integration & Testing

${edges
  .slice(0, 20)
  .map((e) => {
    const src = idToLabel.get(e.source) ?? e.source;
    const tgt = idToLabel.get(e.target) ?? e.target;
    const lbl = (e.data?.label as string)?.trim();
    return `- [ ] Wire **${src}** → **${tgt}**${lbl ? `: ${lbl}` : ""}`;
  })
  .join("\n")}

## Phase 6: Production Readiness

- [ ] Add health check endpoints to all services
- [ ] Set up structured logging
- [ ] Configure error monitoring
- [ ] Write integration tests for critical data flows
- [ ] Performance test under expected load
- [ ] Deploy to staging, then production
`;
}

// ─── Vibe-coder prompts ───────────────────────────────────────────────────────

export function generateLovablePrompt(
  nodes: CanvasNode[],
  edges: CanvasEdge[],
  projectName: string
): string {
  const { frontend, backend, infra, data } = groupNodesByTier(nodes);
  const idToLabel = new Map<string, string>();
  for (const n of nodes) idToLabel.set(n.id, (n.data.label as string) || "Untitled");

  const describeNodes = (arr: CanvasNode[]) =>
    arr.map((n) => {
      const label = (n.data.label as string) || "Untitled";
      const tech = (n.data.configTechnology as string)?.trim();
      const desc = (n.data.description as string)?.trim();
      return `- ${label}${tech ? ` (${tech})` : ""}${desc ? `: ${desc}` : ""}`;
    }).join("\n");

  const pages = frontend.map((n) => `- ${(n.data.label as string) || "Page"}`).join("\n") || "- Dashboard";

  const apiRoutes = backend.map((n) => {
    const label = (n.data.label as string) || "Service";
    const outgoing = edges.filter((e) => e.source === n.id);
    const endpoints = outgoing.map((e) => {
      const lbl = (e.data?.label as string)?.trim();
      return lbl ? `  - ${lbl}` : null;
    }).filter(Boolean).join("\n");
    return `- ${label} service${endpoints ? `\n${endpoints}` : ""}`;
  }).join("\n") || "(define as needed)";

  const dbTech = data
    .map((n) => (n.data.configTechnology as string) || (n.data.configDbType as string) || (n.data.label as string))
    .filter(Boolean)
    .join(", ") || "PostgreSQL";

  return `Build a full-stack web application called "${projectName}".

## Tech Stack
- Framework: Next.js 14+ with App Router
- Styling: Tailwind CSS + shadcn/ui components
- Database: ${dbTech}
- Auth: Clerk authentication
- Deployment: Vercel

## Pages / Views
${pages}

## Backend Services
${describeNodes(backend)}

## API Routes needed
${apiRoutes}

## Infrastructure
${describeNodes(infra)}

## Database Models
${describeNodes(data)}

## Key user flows
${edges.slice(0, 8).map((e) => {
  const src = idToLabel.get(e.source) ?? "Component";
  const tgt = idToLabel.get(e.target) ?? "Component";
  const lbl = (e.data?.label as string)?.trim();
  return `- ${src} → ${tgt}${lbl ? ` via ${lbl}` : ""}`;
}).join("\n") || "- User authenticates and lands on dashboard"}

## Design requirements
- Dark theme with zinc/slate palette
- Premium SaaS aesthetic
- Responsive layout (mobile-first for pages, desktop for dashboards)
- Smooth loading states and error handling
- Toast notifications for user actions

Start with the main layout, navigation, and ${frontend[0] ? (frontend[0].data.label as string) : "dashboard"} page. Then implement the backend services one at a time.`;
}

export function generateV0Prompt(
  nodes: CanvasNode[],
  edges: CanvasEdge[],
  projectName: string
): string {
  const { frontend, backend, data } = groupNodesByTier(nodes);
  const idToLabel = new Map<string, string>();
  for (const n of nodes) idToLabel.set(n.id, (n.data.label as string) || "Untitled");

  const componentList = [
    ...frontend.map((n) => `- ${(n.data.label as string) || "Component"} (page/view)`),
    ...backend.slice(0, 4).map((n) => `- ${(n.data.label as string) || "Component"} (API/service)`),
  ].join("\n") || "- Dashboard page\n- Settings page";

  const dbSchema = data
    .map((n) => `- ${(n.data.label as string) || "Table"} table`)
    .join("\n") || "- Users table";

  return `Create a "${projectName}" web application using Next.js, Tailwind CSS, and shadcn/ui.

## Components needed
${componentList}

## Data models
${dbSchema}

## Connected flows
${edges.slice(0, 6).map((e) => {
  const src = idToLabel.get(e.source) ?? "A";
  const tgt = idToLabel.get(e.target) ?? "B";
  const lbl = (e.data?.label as string)?.trim();
  return `- ${src} → ${tgt}${lbl ? ` (${lbl})` : ""}`;
}).join("\n") || "- User logs in → Dashboard\n- Dashboard → API"}

## Design
- Dark theme with zinc-900 background, zinc-800 cards
- Indigo/violet accent colours
- shadcn/ui components throughout (Button, Card, Input, Dialog, Table)
- Inter font, clean spacing, premium SaaS look
- Subtle borders, no harsh shadows

## Start with
The main layout with sidebar navigation and the ${frontend[0] ? (frontend[0].data.label as string) : "dashboard"} as the default page. Include proper TypeScript types.`;
}

// ─── ZIP bundle download ──────────────────────────────────────────────────────

export async function downloadAgentBundle(
  nodes: CanvasNode[],
  edges: CanvasEdge[],
  projectName: string,
  specMarkdown: string
): Promise<void> {
  const { default: JSZip } = await import("jszip");

  const zip = new JSZip();
  const safe = (projectName || "architecture").replace(/[^a-z0-9]+/gi, "-").toLowerCase();

  const schema = generateSpiSchema(nodes, edges, projectName);
  const claudeMd = generateClaudeMd(nodes, edges, projectName, specMarkdown);
  const tasksMd = generateTasksMd(nodes, edges, projectName);

  zip.file("CLAUDE.md", claudeMd);
  zip.file("ARCHITECTURE.md", specMarkdown);
  zip.file("spi-schema.json", JSON.stringify(schema, null, 2));
  zip.file("TASKS.md", tasksMd);

  const blob = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${safe}-agent-bundle.zip`;
  a.click();
  URL.revokeObjectURL(url);
}

export function downloadSpiSchema(
  nodes: CanvasNode[],
  edges: CanvasEdge[],
  projectName: string
): void {
  const schema = generateSpiSchema(nodes, edges, projectName);
  const blob = new Blob([JSON.stringify(schema, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  const safe = (projectName || "architecture").replace(/[^a-z0-9]+/gi, "-").toLowerCase();
  a.href = url;
  a.download = `${safe}-spi-schema.json`;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── Import validation ────────────────────────────────────────────────────────

export function parseSpiSchema(json: unknown): SpiSchema | null {
  if (!json || typeof json !== "object") return null;
  const obj = json as Record<string, unknown>;
  if (obj.version !== "1") return null;
  if (!Array.isArray(obj.nodes) || !Array.isArray(obj.edges)) return null;
  return obj as unknown as SpiSchema;
}
