import type { CanvasNode, CanvasEdge } from "@/types/canvas";

/** Human-readable labels for the flattened config fields on a node. */
const CONFIG_LABELS: Record<string, string> = {
  configTechnology: "Technology",
  configPort: "Port",
  configProtocol: "Protocol",
  configScaling: "Scaling",
  configDbType: "Database Type",
  configReplication: "Replication",
  configQueueType: "Queue Type",
  configCacheType: "Cache Type",
  configTtl: "TTL",
  configAuthMethod: "Auth Method",
  configRateLimit: "Rate Limit",
  configRuntime: "Runtime",
  configMemory: "Memory",
  configTimeout: "Timeout",
  configPlatform: "Platform",
  configFramework: "Framework",
  configStorageType: "Storage Type",
};

function configEntries(data: CanvasNode["data"]): Array<[string, string]> {
  const out: Array<[string, string]> = [];
  for (const [key, label] of Object.entries(CONFIG_LABELS)) {
    const value = data[key];
    if (typeof value === "string" && value.trim()) {
      out.push([label, value.trim()]);
    }
  }
  return out;
}

interface SpecInput {
  projectName: string;
  nodes: CanvasNode[];
  edges: CanvasEdge[];
  /** Optional AI-written narrative (hybrid mode). */
  overview?: string;
  /** ISO-ish date string for the header; pass from the caller to stay testable. */
  date?: string;
}

/**
 * Deterministic Markdown technical spec built directly from the canvas graph.
 * Accurate and instant; an optional AI `overview` is layered on top (hybrid).
 */
export function generateSpecMarkdown({
  projectName,
  nodes,
  edges,
  overview,
  date,
}: SpecInput): string {
  const lines: string[] = [];
  const title = projectName?.trim() || "Untitled Project";

  lines.push(`# ${title} — System Architecture Spec`);
  lines.push("");
  if (date) {
    lines.push(`_Generated by SYPI · ${date}_`);
    lines.push("");
  }

  if (overview?.trim()) {
    lines.push("## Overview");
    lines.push("");
    lines.push(overview.trim());
    lines.push("");
  }

  // Build a label lookup for readable edge endpoints.
  const idToLabel = new Map<string, string>();
  for (const n of nodes) {
    idToLabel.set(n.id, (n.data.label as string) || "Untitled");
  }

  // --- Components ---
  lines.push(`## Components (${nodes.length})`);
  lines.push("");
  if (nodes.length === 0) {
    lines.push("_No components yet._");
    lines.push("");
  } else {
    lines.push("| Component | Type | Description |");
    lines.push("| --- | --- | --- |");
    for (const n of nodes) {
      const label = (n.data.label as string) || "Untitled";
      const category = (n.data.nodeCategory as string) || "custom";
      const desc = ((n.data.description as string) || "").replace(/\|/g, "\\|").replace(/\n/g, " ");
      lines.push(`| **${label}** | ${category} | ${desc || "—"} |`);
    }
    lines.push("");
  }

  // --- Connections ---
  lines.push(`## Connections (${edges.length})`);
  lines.push("");
  if (edges.length === 0) {
    lines.push("_No connections yet._");
    lines.push("");
  } else {
    for (const e of edges) {
      const source = idToLabel.get(e.source) ?? e.source;
      const target = idToLabel.get(e.target) ?? e.target;
      const label = (e.data?.label as string)?.trim();
      lines.push(`- **${source}** → **${target}**${label ? `: ${label}` : ""}`);
    }
    lines.push("");
  }

  // --- Per-component detail (only for nodes with config or notes) ---
  const detailed = nodes.filter(
    (n) => configEntries(n.data).length > 0 || (n.data.notes as string)?.trim()
  );
  if (detailed.length > 0) {
    lines.push("## Component Details");
    lines.push("");
    for (const n of detailed) {
      const label = (n.data.label as string) || "Untitled";
      const category = (n.data.nodeCategory as string) || "custom";
      lines.push(`### ${label} (${category})`);
      lines.push("");
      const desc = (n.data.description as string)?.trim();
      if (desc) {
        lines.push(desc);
        lines.push("");
      }
      for (const [k, v] of configEntries(n.data)) {
        lines.push(`- **${k}:** ${v}`);
      }
      const notes = (n.data.notes as string)?.trim();
      if (notes) {
        lines.push(`- **Notes:** ${notes}`);
      }
      lines.push("");
    }
  }

  return lines.join("\n").trimEnd() + "\n";
}
