/**
 * System Kit — SYPI's thesis feature.
 *
 * The gap between senior engineers and vibe coders is the proper system:
 * documented context, standards, workflow rules, and a progress tracker.
 * The kit generates that six-file system from the user's actual canvas so
 * any project leaves SYPI with senior-grade discipline, not just a diagram.
 */

export interface KitFileSpec {
  name: string;
  title: string;
  guidance: string;
}

export const KIT_FILES: KitFileSpec[] = [
  {
    name: "project-overview.md",
    title: "Project Overview",
    guidance: `Write project-overview.md: what this system does and why.
Include: a one-paragraph overview; numbered goals (measurable, not aspirational);
the step-by-step core user flow; features grouped by category; an explicit
IN SCOPE list; an explicit OUT OF SCOPE list (infer sensible exclusions);
success criteria that are verifiable ("a signed-in user can X"), not vague.`,
  },
  {
    name: "architecture.md",
    title: "Architecture",
    guidance: `Write architecture.md: the system's structure, derived strictly from the canvas.
Include: a stack table (layer | technology | role) using the ACTUAL technologies in the
component configs; system boundaries (which component owns which responsibility);
the storage model (what lives in each database/cache/storage component); the auth &
access model (from gateway/auth components, or state the gap); and an INVARIANTS
section with at least 4 rules this system must never violate (derived from the design,
e.g. "clients never talk to the database directly").`,
  },
  {
    name: "code-standards.md",
    title: "Code Standards",
    guidance: `Write code-standards.md for the stack visible in the canvas configs
(languages, frameworks, protocols). Include: language conventions; framework patterns;
API design rules matching the protocols in use (REST/gRPC/GraphQL as configured);
file/folder organization; naming conventions; error-handling rules; testing expectations.
Be opinionated and specific to THIS stack — no generic advice.`,
  },
  {
    name: "ai-workflow-rules.md",
    title: "AI Workflow Rules",
    guidance: `Write ai-workflow-rules.md as DIRECT IMPERATIVE COMMANDS to an AI coding agent
building this system. Include: the overall approach (spec-driven, one unit at a time);
scoping rules (no speculative changes, stay within one system boundary per unit);
what to do when requirements are missing (ask, never guess); which things must not be
modified without instruction; how to keep these context files in sync; and a
verification checklist before any unit is marked done (build passes, no type errors,
behavior verified).`,
  },
  {
    name: "ui-context.md",
    title: "UI / Experience Context",
    guidance: `Write ui-context.md. If the canvas has client/frontend components: define the
visual language for them — semantic color-token table (name + hex), typography roles,
spacing/radius scale, component-library conventions, and layout patterns for the app's
actual surfaces. If there is NO client tier, write it as experience-context.md content
instead: the operational interfaces (CLIs, dashboards, alerts, reports) and the
conventions for each. Every visual/interface decision an agent could face should be
answerable from this file.`,
  },
  {
    name: "progress-tracker.md",
    title: "Progress Tracker",
    guidance: `Write progress-tracker.md as the living status file for this build.
Include sections: Current Phase (set to "Foundation — system designed in SYPI, build not started");
Current Goal; Completed (list "System architecture designed" with today's component count);
In Progress (none yet); Next Up — a realistic ordered list of the first 5-8 build units
derived from the architecture (dependencies first: auth before features, backend before
frontend wiring); Open Questions (infer 2-4 real unresolved decisions from the design);
Architecture Decisions (list the key ones already made, from the canvas); Session Notes.`,
  },
];

/** Static entry-point file included in every kit (not AI-generated). */
export function kitEntryFile(projectName: string): string {
  return `# ${projectName} — AI Building Context

> Generated by SYPI (sypi-ai-dev.vercel.app). This is the entry point your
> AI coding agent reads first, every session. Works as CLAUDE.md or AGENTS.md.

## Application Building Context

Read the following files in order before implementing or making any
architectural decision:

1. \`project-overview.md\` — product definition, goals, features, and scope
2. \`architecture.md\` — system structure, boundaries, storage model, and invariants
3. \`ui-context.md\` — theme, interface conventions, and experience patterns
4. \`code-standards.md\` — implementation rules and conventions
5. \`ai-workflow-rules.md\` — development workflow, scoping rules, and delivery approach
6. \`progress-tracker.md\` — current phase, completed work, open questions, next steps

Update \`progress-tracker.md\` after each meaningful implementation change.

If implementation changes the architecture, scope, or standards documented in
these files, update the relevant file before continuing.
`;
}

export const KIT_SYSTEM_PROMPT = `
You are a senior engineer writing ONE file of a project's "proper system" — the
six-file context system that separates disciplined senior-grade builds from vibe
coding. These files will be read by AI coding agents at the start of every session,
so precision beats prose.

RULES:
- Derive everything from the ACTUAL architecture provided (component names, categories,
  configured technologies, connections). Reference real component labels.
- Be specific and concrete. If the canvas doesn't answer something, make ONE reasonable
  decision and state it plainly — never write "TBD" or generic filler.
- Plain Markdown. Start with a single H1 title. No preamble, no closing summary.
- Keep each file focused on its own job — do not repeat content that belongs in the
  other files of the system.
`.trim();
